# Generated by Django 4.2.14 on 2024-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
